///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//import org.junit.Test;
//
//import com.parkinglot.Main;
//
//import static org.junit.Assert.*;
//
//public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//    
//    
//    @Test 
//    public void testFileInput() {
//        Main mainRunner= new Main();
//        String args[]= {"file_input.txt"};
//        mainRunner.main(args);
//         
////        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//    
//    
//    @Test 
//    public void testCreateParkingLot() {
//    	Main mainRunner= new Main();
//        String args[]= {""};
//    	mainRunner.main(args);
////        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//    
//    
//    
//    
//    @Test 
//    public void testParkingAcar() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//    
//    
//    @Test 
//    public void testLeaveAcar() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
